•    Caiky RM - 99274
<BR>
•    Yann RM - 550783
<BR>
•    Lucas RM - 99061

In [1]:
import pandas as pd
import seaborn as sn
import csv as csv

##Previsão da safra da cana de açucar

dataset com as informações das safras

In [2]:
# Read the CSV file
cana = pd.read_csv('Site_PREVISAO_DE_SAFRA-CANA-DE-ACUCAR-AGO-2023.csv', encoding= 'latin1')
cana = cana.dropna()
cana.head(30)

,Tabela 6,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
7,NORTE,72.3,92.7,93.7,21.4,29.6,1.0,1.1
8,RR,-,-,-,-,-,-,-
9,RO,-,-,-,-,-,-,-
10,AC,-,-,-,-,-,-,-
11,AM,12.1,14.9,14.9,2.8,23.3,-,-
12,AP,-,-,-,-,-,-,-
13,PA,60.3,77.8,78.8,18.6,30.9,1.0,1.3
14,TO,-,-,-,-,-,-,-
15,NORDESTE,"3,204.8","3,530.7","3,576.4",371.6,11.6,45.7,1.3
16,MA,26.1,28.4,25.8,(0.4),(1.4),(2.6),(9.2)
17,PI,101.0,104.0,104.0,3.0,3.0,-,-
18,CE,-,-,-,-,-,-,-
19,RN,206.9,229.5,218.7,11.8,5.7,(10.7),(4.7)
20,PB,125.0,125.0,210.5,85.5,68.4,85.5,68.4
21,PE,982.7,"1,004.3","1,103.4",120.7,12.3,99.1,9.9
22,AL,"1,545.8","1,765.0","1,639.4",93.6,6.1,(125.6),(7.1)
23,SE,129.8,124.6,124.6,(5.2),(4.0),-,-
24,BA,87.5,150.0,150.0,62.5,71.4,-,-
25,CENTRO-OESTE,"4,165.0","4,514.3","4,949.1",784.1,18.8,434.8,9.6
26,MT,501.6,534.0,536.3,34.7,6.9,2.3,0.4
27,MS,"1,500.3","1,421.4","1,786.3",286.0,19.1,364.8,25.7
28,GO,"2,163.1","2,558.9","2,626.5",463.4,21.4,67.6,2.6
29,DF,-,-,-,-,0.0,-,0.0
30,SUDESTE,"27,146.0","28,138.4","29,754.8","2,608.8",9.6,"1,616.4",5.7
31,MG,"4,501.9","4,758.6","5,109.2",607.3,13.5,350.6,7.4
32,ES,127.8,153.1,153.1,25.4,19.9,-,-
33,RJ,28.7,25.1,59.7,31.0,108.0,34.6,137.9
34,SP,"22,487.6","23,201.6","24,432.7","1,945.2",8.6,"1,231.1",5.3
35,SUL,"2,218.8","2,495.5","2,519.4",300.6,13.6,23.9,1.0
36,PR,"2,218.8","2,495.5","2,519.4",300.6,13.6,23.9,1.0

renomeei as colunas para os nomes verdadeiros

In [3]:
import pandas as pd

# Supondo que você já tenha o DataFrame "cana"

mapeamento_nomes = {
    'Tabela 6': 'REGIÃO/UF',
    'Unnamed: 1': 'Safra 2022/23(a)',
    'Unnamed: 2': 'Safra 2023/24 Lev. Anterior(b)',
    'Unnamed: 3': 'Safra 2023/24 Lev. Atual(c)',
    'Unnamed: 4': 'Absoluta (c-a)',
    'Unnamed: 5': '% (c/a)',
    'Unnamed: 6': 'Absoluta (c-b)',
    'Unnamed: 7': '% (c/b)'
}

# Remover espaços extras nos nomes das colunas
cana.columns = cana.columns.str.strip()

# Renomear as colunas usando o método rename
cana.rename(columns=mapeamento_nomes, inplace=True)

cana.head(100)

,REGIÃO/UF,Safra 2022/23(a),Safra 2023/24 Lev. Anterior(b),Safra 2023/24 Lev. Atual(c),Absoluta (c-a),% (c/a),Absoluta (c-b),% (c/b)
7,NORTE,72.3,92.7,93.7,21.4,29.6,1.0,1.1
8,RR,-,-,-,-,-,-,-
9,RO,-,-,-,-,-,-,-
10,AC,-,-,-,-,-,-,-
11,AM,12.1,14.9,14.9,2.8,23.3,-,-
12,AP,-,-,-,-,-,-,-
13,PA,60.3,77.8,78.8,18.6,30.9,1.0,1.3
14,TO,-,-,-,-,-,-,-
15,NORDESTE,"3,204.8","3,530.7","3,576.4",371.6,11.6,45.7,1.3
16,MA,26.1,28.4,25.8,(0.4),(1.4),(2.6),(9.2)
17,PI,101.0,104.0,104.0,3.0,3.0,-,-
18,CE,-,-,-,-,-,-,-
19,RN,206.9,229.5,218.7,11.8,5.7,(10.7),(4.7)
20,PB,125.0,125.0,210.5,85.5,68.4,85.5,68.4
21,PE,982.7,"1,004.3","1,103.4",120.7,12.3,99.1,9.9
22,AL,"1,545.8","1,765.0","1,639.4",93.6,6.1,(125.6),(7.1)
23,SE,129.8,124.6,124.6,(5.2),(4.0),-,-
24,BA,87.5,150.0,150.0,62.5,71.4,-,-
25,CENTRO-OESTE,"4,165.0","4,514.3","4,949.1",784.1,18.8,434.8,9.6
26,MT,501.6,534.0,536.3,34.7,6.9,2.3,0.4
27,MS,"1,500.3","1,421.4","1,786.3",286.0,19.1,364.8,25.7
28,GO,"2,163.1","2,558.9","2,626.5",463.4,21.4,67.6,2.6
29,DF,-,-,-,-,0.0,-,0.0
30,SUDESTE,"27,146.0","28,138.4","29,754.8","2,608.8",9.6,"1,616.4",5.7
31,MG,"4,501.9","4,758.6","5,109.2",607.3,13.5,350.6,7.4
32,ES,127.8,153.1,153.1,25.4,19.9,-,-
33,RJ,28.7,25.1,59.7,31.0,108.0,34.6,137.9
34,SP,"22,487.6","23,201.6","24,432.7","1,945.2",8.6,"1,231.1",5.3
35,SUL,"2,218.8","2,495.5","2,519.4",300.6,13.6,23.9,1.0
36,PR,"2,218.8","2,495.5","2,519.4",300.6,13.6,23.9,1.0
37,SC,-,-,-,-,-,-,-
38,RS,-,-,-,-,-,-,-
39,NORTE/NORDESTE,"3,277.1","3,623.4","3,670.1",393.0,12.0,46.7,1.3
40,CENTRO-SUL,"33,529.8","35,148.2","37,223.3","3,693.5",11.0,"2,075.1",5.9
41,BRASIL,"36,806.9","38,771.6","40,893.4","4,086.5",11.1,"2,121.8",5.5

filtramos pelo estado de SP

In [4]:
linha_sp = cana[cana["REGIÃO/UF"] == "SP"]
linha_sp

,REGIÃO/UF,Safra 2022/23(a),Safra 2023/24 Lev. Anterior(b),Safra 2023/24 Lev. Atual(c),Absoluta (c-a),% (c/a),Absoluta (c-b),% (c/b)
34,SP,"22,487.6","23,201.6","24,432.7","1,945.2",8.6,"1,231.1",5.3

calculo do score
<br>
insira a baixo sem pontos ou virgulas a safra referente a sp ou outro estado do DF

In [5]:
# Definindo os presets
presets = [
    {"classificacao": "Excelente", "peso": 0.15, "limite_inferior": 4.1, "limite_superior": float("inf")},
    {"classificacao": "Muito bom", "peso": 0.135, "limite_inferior": 2.5, "limite_superior": 4.0},
    {"classificacao": "Bom", "peso": 0.105, "limite_inferior": 1.5, "limite_superior": 2.4},
    {"classificacao": "Regular", "peso": 0.075, "limite_inferior": 0.0, "limite_superior": 1.4},
    {"classificacao": "Ruim", "peso": 0.045, "limite_inferior": -1.5, "limite_superior": -0.001},
    {"classificacao": "Muito ruim", "peso": 0.015, "limite_inferior": float("-inf"), "limite_superior": -1.5}
]

# Função para calcular a pontuação com base na expectativa de produção
def calcular_pontuacao(expectativa):
    for preset in presets:
        if preset["limite_inferior"] <= expectativa <= preset["limite_superior"]:
            return preset["peso"] * 15
    return 0

# Obtendo a expectativa de produção do usuário
expectativa_producao = float(input("Digite a expectativa de produção: "))

# Calculando a pontuação
pontuacao = calcular_pontuacao(expectativa_producao)

# Exibindo o resultado
print("Pontuação:", pontuacao)

Digite a expectativa de produção: 22365482
Pontuação: 2.25

##Taxa de inadimplência

In [6]:

# Read the CSV file
t_inadimplencia = pd.read_csv('taxa_inadimplência.csv', encoding= 'latin1')
t_inadimplencia = t_inadimplencia.dropna()
t_inadimplencia.head(50)

                 Data;26800 - Taxa de inadimplência por origem dos recursos e modalidade de crédito - MEI - Recursos direcionados - Financiamento rural - investimento - %
1° Trim.2016;8                                                 9.0
2° Trim.2016;10                                                6.0
3° Trim.2016;11                                                5.0
4° Trim.2016;13                                                0.0
1° Trim.2017;10                                                1.0
2° Trim.2017;5                                                 3.0
3° Trim.2017;0                                                 0.0
4° Trim.2017;0                                                 0.0
1° Trim.2018;0                                                 0.0
2° Trim.2018;0                                                 0.0
3° Trim.2018;0                                                 0.0
4° Trim.2018;0                                                 0.0
1° Trim.2020;0                                                 0.0
2° Trim.2020;0                                                 0.0
3° Trim.2020;0                                                 0.0
4° Trim.2020;0                                                 0.0
1° Trim.2021;0                                                 0.0
2° Trim.2021;0                                                 0.0
3° Trim.2021;0                                                 0.0
4° Trim.2021;0                                                 0.0
1° Trim.2022;0                                                 0.0
2° Trim.2022;0                                                 0.0
3° Trim.2022;23                                                4.0
4° Trim.2022;19                                                6.0

In [ ]:
novos_nomes_colunas = {
    "Taxa de Inadimplência": "Taxa Inadimplência Produtores Rurais",
    "Resultado Pontos score": "Resultado Pontos Score"
}

# Renomear as colunas
df.rename(columns=novos_nomes_colunas, inplace=True)

# Exibir o DataFrame com as colunas renomeadas
print(df)

In [7]:
# Definindo os presets
presets = [
    {"classificacao": "Muito ruim", "peso": 0.10, "limite_inferior": 25.1, "limite_superior": float("inf")},
    {"classificacao": "Ruim", "peso": 0.30, "limite_inferior": 20.1, "limite_superior": 25.0},
    {"classificacao": "Regular", "peso": 0.50, "limite_inferior": 15.1, "limite_superior": 20.0},
    {"classificacao": "Bom", "peso": 0.70, "limite_inferior": 10.1, "limite_superior": 15.0},
    {"classificacao": "Muito bom", "peso": 0.90, "limite_inferior": 5.1, "limite_superior": 10.0},
    {"classificacao": "Excelente", "peso": 1.00, "limite_inferior": 0.0, "limite_superior": 5.0}
]

# Função para calcular o resultado pontos score
def calcular_pontos_score(taxa_inadimplencia):
    for preset in presets:
        if preset["limite_inferior"] <= taxa_inadimplencia <= preset["limite_superior"]:
            return preset["peso"] * 0.25 * 100  # Multiplicando por 0.25 para obter o valor de 25%
    return 0

# Obtendo a taxa de inadimplência dos produtores rurais do usuário
taxa_inadimplencia = float(input("Digite a taxa de inadimplência dos produtores rurais: "))

# Calculando o resultado pontos score
resultado_score = calcular_pontos_score(taxa_inadimplencia)

# Exibindo o resultado
print("Resultado Pontos score:", resultado_score)

Digite a taxa de inadimplência dos produtores rurais: 4
Resultado Pontos score: 25.0